name: newbankapp
description: A new Flutter project of a bank app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  mobx:
  flutter_mobx:
  provider:
  cupertino_icons: ^1.0.2
  localization: ^2.1.0
  flutter_svg_provider: ^1.0.3
  flutter_triple: ^1.2.7+4
  flutter_modular: ^5.0.3
  dio: ^5.1.0
  introduction_screen: ^3.1.8
  flip_card: ^0.7.0

dev_dependencies:
  mobx_codegen:
  build_runner:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  
  assets:
    - lib/assets/
    - lib/assets/i18n/
    - lib/assets/images/
    - lib/assets/icons/
  
  fonts:
    - family: Billabong
      fonts:
        - asset: lib/assets/fonts/Billabong.ttf   
    - family: Cormorant
      fonts:
        - asset: lib/assets/fonts/CormorantGaramond.ttf
    - family: Raleway
      fonts:
        - asset: lib/assets/fonts/Raleway-Regular.ttf
        - asset: lib/assets/fonts/Raleway-Bold.ttf
          weight: 700